DIRTY_NONE   = 0
DIRTY_HEADER = 1 << 0
DIRTY_PAGE   = 1 << 1
DIRTY_TILES  = 1 << 2
DIRTY_TILE0  = 1 << 3
DIRTY_TILE1  = 1 << 4
DIRTY_TILE2  = 1 << 5
DIRTY_ALL = (
    DIRTY_HEADER
    | DIRTY_PAGE
    | DIRTY_TILES
    | DIRTY_TILE0
    | DIRTY_TILE1
    | DIRTY_TILE2
)
